import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed": "#100563",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#4edea3",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#005236",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-error-container": "#93000a",
        "secondary-container": "#6cf8bb",
        "primary-fixed-dim": "#c3c0ff",
        "tertiary-container": "#393942",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed-variant": "#3e3c8f",
        "error": "#ba1a1a",
        "secondary": "#006c49",
        "tertiary": "#23242c",
        "surface-dim": "#cbdbf5",
        "on-secondary-container": "#00714d",
        "on-tertiary-fixed": "#1a1b23",
        "tertiary-fixed": "#e3e1ed",
        "on-background": "#0b1c30",
        "primary-container": "#312e81",
        "outline": "#777682",
        "on-secondary-fixed": "#002113",
        primary: "#4F46E5",
        "surface-container-low": "#eff4ff",
        "on-error": "#ffffff",
        "surface-container": "#e5eeff",
        "on-primary-container": "#9c9af4",
        "on-surface": "#0b1c30",
        "on-tertiary-container": "#a3a3ad",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary-fixed-variant": "#46464f",
        "primary-fixed": "#e2dfff",
        surface: "#f8f9ff",
        "on-surface-variant": "#474651",
        "surface-tint": "#5654a8",
        "outline-variant": "#c8c5d3",
        "inverse-primary": "#c3c0ff",
        "on-primary": "#ffffff",
        "inverse-surface": "#213145",
        "tertiary-fixed-dim": "#c7c5d1"
      },
    },
  },
  plugins: [],
};
export default config;
